version: '3.7'
services:
  angular:
    hostname: localhost
    build: 
      context: .
      dockerfile: Dockerfile-Browser
    ports:
      - 80:80
  express:
    build: 
      context: .
      dockerfile: Dockerfile-Server
    ports:
      - "3000:3000"