FROM node:current
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install
RUN npm install -g @angular/cli
COPY . /app
RUN npm run build:ssr
EXPOSE 4000
CMD ["npm", "run", "serve:ssr"]